/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Emmanuel
 */
public class GUI_RevisionMatricula extends javax.swing.JPanel {

    /**
     * Creates new form GUI_RevisionMatricula
     */
    public GUI_RevisionMatricula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLMatriculados = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cédula.");
        add(jLabel1);
        jLabel1.setBounds(20, 0, 80, 30);
        add(jTextField1);
        jTextField1.setBounds(20, 30, 120, 20);

        jScrollPane1.setViewportView(jLMatriculados);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 150, 90, 130);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cursos Matrículados.");
        add(jLabel2);
        jLabel2.setBounds(20, 120, 110, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad de Creditos Matrículados.");
        add(jLabel3);
        jLabel3.setBounds(140, 110, 168, 40);
        add(jSeparator1);
        jSeparator1.setBounds(0, 110, 570, 20);
        add(jTextField2);
        jTextField2.setBounds(140, 150, 50, 30);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nombre.");
        add(jLabel4);
        jLabel4.setBounds(280, 0, 70, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dirección.");
        add(jLabel5);
        jLabel5.setBounds(20, 50, 60, 20);
        add(jTextField3);
        jTextField3.setBounds(20, 70, 250, 30);
        add(jTextField4);
        jTextField4.setBounds(280, 30, 160, 20);

        jBBuscar.setText("Buscar");
        add(jBBuscar);
        jBBuscar.setBounds(150, 30, 100, 20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JList jLMatriculados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
