/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_JF_MantenimientoEstudiantes;
import java.awt.event.ActionListener;

/**
 *
 * @author Emmanuel
 */
public class GUI_Botones extends javax.swing.JPanel {
ActionListener controlador;
    /**
     * Creates new form GUI_Botones
     */
    public GUI_Botones() {
        initComponents();
    }
     public void agregarEventos(ActionListener controlador){
         this.controlador=controlador;
         this.jBAgregar.addActionListener(controlador);
         this.jBBuscar.addActionListener(controlador);
         this.jBEditar.addActionListener(controlador);
         this.jBEliminar.addActionListener(controlador);
     }
     public void desactivarBotones(){
         jBEditar.setEnabled(false);
         jBEliminar.setEnabled(false);
     }
     
     public void activarBotones(){
         jBEditar.setEnabled(true);
         jBEliminar.setEnabled(true); 
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBBuscar = new javax.swing.JButton();
        jBAgregar = new javax.swing.JButton();
        jBEditar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();

        setToolTipText("");
        setOpaque(false);
        setLayout(null);

        jBBuscar.setBackground(new java.awt.Color(0, 102, 102));
        jBBuscar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBBuscar.setForeground(new java.awt.Color(0, 102, 102));
        jBBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Emmanuel\\Documents\\NetBeansProjects\\Ejercicio01\\src\\img\\Bus_car.png")); // NOI18N
        jBBuscar.setToolTipText("Buscar");
        jBBuscar.setActionCommand("Buscar");
        jBBuscar.setOpaque(false);
        add(jBBuscar);
        jBBuscar.setBounds(20, 0, 80, 50);

        jBAgregar.setBackground(new java.awt.Color(0, 102, 102));
        jBAgregar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBAgregar.setForeground(new java.awt.Color(0, 102, 102));
        jBAgregar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Emmanuel\\Documents\\NetBeansProjects\\Ejercicio01\\src\\img\\Guar_dar.png")); // NOI18N
        jBAgregar.setToolTipText("Guardar");
        jBAgregar.setActionCommand("Guardar");
        jBAgregar.setOpaque(false);
        add(jBAgregar);
        jBAgregar.setBounds(100, 0, 80, 50);

        jBEditar.setBackground(new java.awt.Color(0, 102, 102));
        jBEditar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Emmanuel\\Documents\\NetBeansProjects\\Ejercicio01\\src\\img\\Edi_tar.png")); // NOI18N
        jBEditar.setToolTipText("Editar");
        jBEditar.setActionCommand("Editar");
        jBEditar.setOpaque(false);
        add(jBEditar);
        jBEditar.setBounds(180, 0, 80, 50);

        jBEliminar.setBackground(new java.awt.Color(0, 102, 102));
        jBEliminar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jBEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Emmanuel\\Documents\\NetBeansProjects\\Ejercicio01\\src\\img\\Elimi_nar.png")); // NOI18N
        jBEliminar.setToolTipText("Eliminar");
        jBEliminar.setActionCommand("Eliminar");
        jBEliminar.setOpaque(false);
        add(jBEliminar);
        jBEliminar.setBounds(260, 0, 80, 50);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBEditar;
    private javax.swing.JButton jBEliminar;
    // End of variables declaration//GEN-END:variables
}
