/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorUsuarios;
import Modelo.ConexionBD;

/**
 *
 * @author Emmanuel
 */
public class JF_EleccionGuardado extends javax.swing.JFrame {
private int tipoGuardado;
    /**
     * Creates new form JF_EleccionGuardado
     */
    private ConexionBD conexionBD;
    JF_MenuPrincipal jf_Principal;
    JF_Usuario usuario;
    ControladorUsuarios controladorUsuarios;
    Principal principal;
    public JF_EleccionGuardado(ConexionBD conexionBD,Principal principal) {
        initComponents();
        this.conexionBD=conexionBD;
        this.grupoBotones.add(this.jRB_BaseDatos);
         this.grupoBotones.add(this.jRB_ArchivosPlanos);
          this.grupoBotones.add(this.jRB_Xtml);
          this.principal=principal;
          setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        jL_Pregunta = new javax.swing.JLabel();
        jRB_BaseDatos = new javax.swing.JRadioButton();
        jRB_Xtml = new javax.swing.JRadioButton();
        jRB_ArchivosPlanos = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 0));
        setMinimumSize(new java.awt.Dimension(384, 273));
        setResizable(false);
        getContentPane().setLayout(null);

        jL_Pregunta.setFont(new java.awt.Font("Masque", 0, 8)); // NOI18N
        jL_Pregunta.setForeground(new java.awt.Color(214, 217, 223));
        jL_Pregunta.setText("Escoja la forma en que desea guardar los datos.");
        getContentPane().add(jL_Pregunta);
        jL_Pregunta.setBounds(40, 30, 370, 70);

        jRB_BaseDatos.setFont(new java.awt.Font("Masque", 0, 12)); // NOI18N
        jRB_BaseDatos.setForeground(new java.awt.Color(214, 217, 223));
        jRB_BaseDatos.setSelected(true);
        jRB_BaseDatos.setText("Base de Datos.");
        jRB_BaseDatos.setContentAreaFilled(false);
        getContentPane().add(jRB_BaseDatos);
        jRB_BaseDatos.setBounds(40, 90, 140, 23);

        jRB_Xtml.setFont(new java.awt.Font("Masque", 0, 12)); // NOI18N
        jRB_Xtml.setForeground(new java.awt.Color(214, 217, 223));
        jRB_Xtml.setText("XTML.");
        jRB_Xtml.setContentAreaFilled(false);
        getContentPane().add(jRB_Xtml);
        jRB_Xtml.setBounds(40, 120, 70, 23);

        jRB_ArchivosPlanos.setFont(new java.awt.Font("Masque", 0, 12)); // NOI18N
        jRB_ArchivosPlanos.setForeground(new java.awt.Color(214, 217, 223));
        jRB_ArchivosPlanos.setText("Archivos Planos.");
        jRB_ArchivosPlanos.setContentAreaFilled(false);
        getContentPane().add(jRB_ArchivosPlanos);
        jRB_ArchivosPlanos.setBounds(40, 150, 170, 23);

        jButton1.setFont(new java.awt.Font("Masque", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 0));
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Emmanuel\\Documents\\NetBeansProjects\\Ejercicio01\\src\\img\\Aceptar.png")); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 180, 140, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Emmanuel\\Documents\\NetBeansProjects\\Ejercicio01\\src\\img\\Guar_dar.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 10, 50, 40);

        jLabel3.setFont(new java.awt.Font("Masque", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 238, 238));
        jLabel3.setText("Método Guardado.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 20, 190, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Emmanuel\\Documents\\NetBeansProjects\\Ejercicio01\\src\\img\\UsersFondo.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-600, -110, 1120, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        if(jRB_BaseDatos.isSelected()==true){
          tipoGuardado=1;
      }
      if(jRB_Xtml.isSelected()==true){
          tipoGuardado=2;
      }
      
      if(jRB_ArchivosPlanos.isSelected()==true){
          tipoGuardado=3;
      }
////      jf_Principal=new JF_MenuPrincipal(conexionBD,tipoGuardado);
//      ControladorUsuarios controladorUsuarios=new ControladorUsuarios(tipoGuardado,conexionBD);
//      this.controladorUsuarios=controladorUsuarios;
//      procesoInicio();
      principal.inicio();
      this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    public int getTipoGuardado(){
        return tipoGuardado;
    }
//    public void procesoInicio(){
//        JF_Usuario usuario=new JF_Usuario(controladorUsuarios);
//        JF_MantenimientoUsuarios mantenimientoUsuarios=new JF_MantenimientoUsuarios(controladorUsuarios);
//        if(controladorUsuarios.corroborarExistenciaUsuarios()){
//            usuario.setVisible(true);
//            
//        }else{
//            
//        }
//        controladorUsuarios.setVentaUsuario(usuario);
//    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jL_Pregunta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRB_ArchivosPlanos;
    private javax.swing.JRadioButton jRB_BaseDatos;
    private javax.swing.JRadioButton jRB_Xtml;
    // End of variables declaration//GEN-END:variables
}
