/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_JF_MantenimientoEstudiantes;
import Modelo.ConexionBD;
import Modelo.MetodosEstudiantes;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Emmanuel
 */
public class JF_MantenimientoEstudiantes extends javax.swing.JFrame {

    /**
     * Creates new form JF_MantenimientoEstudiantes
     */
    Controlador_JF_MantenimientoEstudiantes controlador_JF_MantenimientoEstudiantes;
    public JF_MantenimientoEstudiantes(MetodosEstudiantes metodosEstudiantes,ConexionBD conexionBD, int tipoGuardado) {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\Emmanuel\\Documents\\NetBeansProjects\\Ejercicio01\\src\\img\\Student_Icono.png"));
         setVisible(false);
        controlador_JF_MantenimientoEstudiantes= new Controlador_JF_MantenimientoEstudiantes(this,metodosEstudiantes,tipoGuardado);
        gUI_Botones1.agregarEventos(controlador_JF_MantenimientoEstudiantes);
        desactivarBotones();
    }
    public void desactivarBotones(){
        gUI_Botones1.desactivarBotones();
    }
    public void activarBotones(){
        gUI_Botones1.activarBotones();
    }
   public String[] devolverInformacion(){
       return this.gUI_InformacionEstudiante1.devolverInformacion();
   }
    public String devolverCedula(){
         return this.gUI_InformacionEstudiante1.devolverCedula();
    }
    public String devolverNombre(){
         return this.gUI_InformacionEstudiante1.devolverNombre();
    }
    public String devolverDireccion(){
         return this.gUI_InformacionEstudiante1.devolverDireccion();
    }
    public void mostrarInformacion(String[] info){
       gUI_InformacionEstudiante1.setDatos(info);
       activarBotones();
    }
    public void activarMensaje(String mensaje){
    JOptionPane.showMessageDialog(null,mensaje);
}
    public void desactivarCasillaCedula(){
        gUI_InformacionEstudiante1.desactivarCasillaCedula();
    }
    public void limpiarCampos(){
         gUI_InformacionEstudiante1.limpiar();
         desactivarBotones();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_Botones1 = new Vista.GUI_Botones();
        gUI_InformacionEstudiante1 = new Vista.GUI_InformacionEstudiante();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Estudiantes");
        setLocation(new java.awt.Point(300, 0));
        setMinimumSize(new java.awt.Dimension(530, 420));
        setResizable(false);
        getContentPane().setLayout(null);

        gUI_Botones1.setBackground(new java.awt.Color(201, 201, 201));
        getContentPane().add(gUI_Botones1);
        gUI_Botones1.setBounds(70, 190, 550, 73);
        getContentPane().add(gUI_InformacionEstudiante1);
        gUI_InformacionEstudiante1.setBounds(90, 60, 308, 131);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Emmanuel\\Documents\\NetBeansProjects\\Ejercicio01\\src\\img\\Student_Icono.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 0, 70, 60);

        jLabel3.setFont(new java.awt.Font("Masque", 1, 24)); // NOI18N
        jLabel3.setText("Estudiantes.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 20, 220, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(170, 50, 210, 10);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Emmanuel\\Documents\\NetBeansProjects\\Ejercicio01\\src\\img\\FondoEstudiantes.png")); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setMinimumSize(new java.awt.Dimension(598, 450));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-190, -20, 750, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_InformacionEstudiante gUI_InformacionEstudiante1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
