/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_JF_Cursos;
import Modelo.ConexionBD;
import Modelo.Cursos;
import Modelo.MetodosCursos;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Emmanuel
 */
public class JF_MantenimientoCursos extends javax.swing.JFrame {

    /**
     * Creates new form JF_MantenimientoCursos
     */
    Controlador_JF_Cursos controlador;
    public JF_MantenimientoCursos(MetodosCursos metodosCursos,ConexionBD conexionBD,int tipoGuardado) {
        initComponents();
        this.setIconImage(Toolkit.getDefaultToolkit().getImage("C:\\Users\\Emmanuel\\Documents\\NetBeansProjects\\Ejercicio01\\src\\img\\Booklet_Icono.png"));
        setVisible(false);
        controlador=new Controlador_JF_Cursos(this,metodosCursos,conexionBD,tipoGuardado);
        gUI_Botones1.agregarEventos(controlador);
        desactivarBotones();
    }
    public void desactivarBotones(){
        gUI_Botones1.desactivarBotones();
    }
    
    public void activarMensaje(String mensaje){
    JOptionPane.showMessageDialog(null,mensaje);
    }
    public void desactivarCasillaSiglas(){
        gUI_Cursos1.desactivarCasillaSiglas();
    }
    public void activarBotones(){
        gUI_Botones1.activarBotones();
    }
    public void limpiarCampos(){
         gUI_Cursos1.limpiarCampos();
    }
    public String devolverSigla(){
        return this.gUI_Cursos1.devolverSigla();
    }
    public String devolverNombre(){
        return gUI_Cursos1.getNombre();
    }
    public Cursos agregarCurso(){
        Cursos curso;
        curso=new Cursos(gUI_Cursos1.devolverSigla(),gUI_Cursos1.getNombre(),gUI_Cursos1.getCreditos());
       return curso;
    }
    public String[] getInformacion(){
        String[] info=new String[3];
        info[0]=gUI_Cursos1.devolverSigla();
        info[1]=gUI_Cursos1.getNombre();
        info[2]=gUI_Cursos1.getCreditos();
        return info;
    }
    public void mostrarInformacion(String[] info){
        gUI_Cursos1.setDatos(info[1], info[2]);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_Botones1 = new Vista.GUI_Botones();
        jLabel2 = new javax.swing.JLabel();
        gUI_Cursos1 = new Vista.GUI_Cursos();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Cursos");
        setLocation(new java.awt.Point(300, 0));
        setMinimumSize(new java.awt.Dimension(552, 450));
        setResizable(false);
        getContentPane().setLayout(null);
        getContentPane().add(gUI_Botones1);
        gUI_Botones1.setBounds(40, 190, 550, 60);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Emmanuel\\Documents\\NetBeansProjects\\Ejercicio01\\src\\img\\Booklet_Icono.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 10, 90, 50);

        gUI_Cursos1.setOpaque(false);
        getContentPane().add(gUI_Cursos1);
        gUI_Cursos1.setBounds(40, 30, 390, 290);

        jLabel3.setFont(new java.awt.Font("Masque", 1, 24)); // NOI18N
        jLabel3.setText("Cursos.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 20, 130, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(180, 50, 120, 10);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Emmanuel\\Documents\\NetBeansProjects\\Ejercicio01\\src\\img\\FondoCursos.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-230, -150, 990, 990);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones1;
    private Vista.GUI_Cursos gUI_Cursos1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
